version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/bot-telegram
permissions:
    - object: /home/ubuntu
      owner: ubuntu
      group: ubuntu
      type:
          - directory
          - file
hooks:
    ApplicationStart:
        - location: start.sh
          timeout: 300
